name: "YAML value override"
description: "YAML value override"
inputs:
  file:
    description: "file to change"
    default: "values.yaml"
  values:
    description: "values for override"
  type:
    default: yaml
    enum:
      - yaml
      - yq
      - yq_multiline
runs:
  using: "node20"
  main: "index.js"
